---
title: Mackaber's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Mackaber's Blog
highlighter: true
jekyll-archives:
  enabled: 
    - tags
    - categories
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    css: class
    line_numbers: false
github:
  repository: mackaber/Mackaber.github.io
plugins:
  - jekyll-archives
  - jekyll-debug
  - kramdown-syntax-coderay
  - jekyll-feed

