---
title: Mackaber's Personal Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: The web is my enemy
markdown: redcarpet
highlighter: true
tag_feed_layout: tag_page
tag_feed_dir: tag
tag_permalink_style: pretty
