---
title: Mackaber's Personal Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Mackaber's Personal Site
markdown: redcarpet
highlighter: true
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
plugins:
  - jekyll-archives
  - jekyll-debug

